// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAllCluster = "all_cluster"

// AllCluster mapped from table <all_cluster>
type AllCluster struct {
	Cluster string `gorm:"column:Cluster;type:varchar(64);primaryKey" json:"Cluster"`
	DB      string `gorm:"column:DB;type:varchar(64);primaryKey" json:"DB"`
}

// TableName AllCluster's table name
func (*AllCluster) TableName() string {
	return TableNameAllCluster
}
